= pki Tool

:OPENXPKI: https://github.com/openxpki/openxpki
:IETF:     https://datatracker.ietf.org/doc/html
:RFC7030:  {IETF}/rfc7030
:RFC8894:  {IETF}/rfc8894

== Synopsis

----
pki --gen     (-g)  generate a new private key
pki --self    (-s)  create a self signed certificate
pki --issue   (-i)  issue a certificate using a CA certificate and key
pki --signcrl (-c)  issue a CRL using a CA certificate and key
pki --acert   (-z)  issue an attribute certificate
pki --req     (-r)  create a PKCS#10 certificate request
pki --pkcs7   (-7)  PKCS#7 wrap/unwrap functions
pki --pkcs12  (-u)  PKCS#12 functions
pki --keyid   (-k)  calculate key identifiers of a key/certificate
pki --print   (-a)  print a credential in a human readable form
pki --dn      (-d)  extract the subject DN of an X.509 certificate
pki --pub     (-p)  extract the public key from a private key/certificate
pki --verify  (-v)  verify a certificate using the CA certificate
pki --scep    (-S)  Enroll an X.509 certificate with a SCEP server
pki --scepca  (-C)  Get CA [and RA] certificate[s] from a SCEP server
pki --est     (-E)  Enroll an X.509 certificate with an EST server
pki --estca   (-e)  Get CA certificate[s] from an EST server
pki --help    (-h)  show usage information
----

== Description

The `*pki*` command suite allows you to run a simple public key infrastructure.
Generate RSA, ECDSA or EdDSA public key pairs, create PKCS#10 certificate requests
containing subjectAltNames, create X.509 self-signed end entity and root CA
certificates, issue end entity and intermediate CA certificates signed by the
private key of a CA and containing `subjectAltNames`, CRL distribution points and
URIs of OCSP servers. You can also extract raw public keys from private keys,
certificate requests and certificates and compute two kinds of SHA1-based key IDs.

[NOTE]
====
Starting with version 5.9.8, the `*pki*` command supports certificate enrollment
via the *Simple Certificate Enrollment Protocol* (SCEP) as defined by
{RFC8894}[RFC 8894], replacing the obsoleted
xref:tools/scepclient.adoc[`*ipsec scepclient*`] tool.

Additionally, with version 5.9.8 the newer `*https*` based *Enrollment over Secure
Transport* (EST) protocol ({RFC7030}[RFC 7030]) is being offered, too.
====

== Subcommands

[cols="1,1,1,1"]
|===
|xref:./pkiGen.adoc[`pki --gen`]
|xref:./pkiSelf.adoc[`pki --self`]
|xref:./pkiPrint.adoc[`pki --print`]
|xref:./pkiPkcs7.adoc[`pki --pkcs7`]

|xref:./pkiKeyid.adoc[`pki --keyid`]
|xref:./pkiIssue.adoc[`pki --issue`]
|xref:./pkiAcert.adoc[`pki --acert`]
|xref:./pkiPkcs12.adoc[`pki --pkcs12`]

|xref:./pkiPub.adoc[`pki --pub`]
|xref:./pkiSignCrl.adoc[`pki --signcrl`]
|xref:./pkiVerify.adoc[`pki --verify`]
|xref:./pkiDn.adoc[`pki --dn`]

|xref:./pkiReq.adoc[`pki --req`]
|xref:./pkiScepCa.adoc[`pki --scepca`]
|xref:./pkiScep.adoc[`pki --scep`]
|

|
|xref:./pkiEstCa.adoc[`pki --estca`]
|xref:./pkiEst.adoc[`pki --est`]
|
|===

Each subcommand has additional options. Pass `*--help*` to a subcommand to get
additional information.

== Configuration

The following parameters can be configured in the
xref:config/strongswanConf.adoc#_pki[`*pki*`] section of
xref:config/strongswanConf.adoc[`*strongswan.conf*`]:

[cols="2,1,10"]
|===
|Key |Default |Description

include::partial$config/pki.adoc[]
|===

== Tutorial

* A xref:./pkiQuickstart.adoc[quickstart] tutorial on the use of the `*pki*` tool
can be found xref:./pkiQuickstart.adoc[here].
