= NAT Traversal

:IETF:    https://datatracker.ietf.org/doc/html
:RFC3947: {IETF}/rfc3947
:RFC3948: {IETF}/rfc3948
:RFC7296: {IETF}/rfc7296

NOTE: The {RFC7296}[IKEv2] protocol includes *NAT Traversal* (NAT-T) in the core
      standard but it is optional to implement for vendors. The strongSwan
      xref:daemons/charon.adoc[`*charon*`] daemon implements *NAT-Traversal*
      without any special prior configuration but the mechanism cannot be disabled,
      either.

NOTE: If you don't like the automatic port floating to UDP port `*4500*` due to the
      xref:features/mobike.adoc[MOBIKE] protocol which happens even if no NAT
      situation exists, then you can disable xref:features/mobike.adoc[MOBIKE] by
      setting `*mobike = no*` in the xref:swanctl/swanctlConf.adoc[`*swanctl.conf*`]
      connection definition.

include::partial$nat-t/natTraversal.adoc[]

== ESP-in-UDP Encapsulation

include::partial$nat-t/espInUdpEncapsulation.adoc[]

== Non-ESP Marker

include::partial$nat-t/nonEspMarker.adoc[]

The insertion of a *Non-ESP Marker* means that the default UDP `*4500*` socket/port
has to handle traffic differently from the default IKE UDP `*500*` socket/port.
This has some implications when using a
xref:#_custom_server_ports[custom server port] (see below).

== NAT-T Keepalives

include::partial$nat-t/keepalives.adoc[]

== Custom Server Ports

When using custom server ports, the client for simplicity only uses a single remote
port configured with `*remote_port*` in
xref:swanctl/swanctlConf.adoc[`*swanctl.conf*`]. This means that there will not be
a port switch while establishing the connection. As described above, if UDP
encapsulation is used, the ESP packets are sent on the ports already used for IKE
traffic. Therefore, the server must be prepared to process UDP-encapsulated ESP
packets on that custom port and consequently is only able to accept IKE packets
with non-ESP marker on it. That in turn forces the client to send all its IKE
packets (including the initial `IKE_SA_INIT` request) with a non-ESP marker.
Otherwise they would be treated as UDP-encapsulated ESP packets.

This has implications for the client and the server configuration:

Server::
Because the client has to connect to a socket/port that is prepared to process
UDP-encapsulated ESP packets, the correct setting to specify a custom port is
`*charon.port_nat_t*`. The `*charon.port*` setting is not relevant in this scenario
(i.e. the default socket/port will not be used, hence inbound traffic to port 500
could be blocked).

Client::
The client must add a non-ESP marker when sending IKE packets to a custom server
port or port 4500. strongSwan adds one if neither source nor destination port is 500.
This means the client can't use port 500 in order to already add a non-ESP
marker when sending the initial `IKE_SA_INIT` request. This can be achieved by
either setting the local port used for IKE (`*local_port*` in
xref:swanctl/swanctlConf.adoc[`*swanctl.conf*`]) to 4500 or by setting
`*charon.port*` on the client to either `*0*` to allocate a random port or any
number != 500 (if that port is not used by any other process), so that the source
port won't be 500 and does not have to be set explicitly in the connection config.
If the latter is done, the client will, however, switch to the second source port
configured via `*charon.port_nat_t*` if a NAT situation is detected or MOBIKE is
enabled, so setting both to `*0*` usually makes most sense for mobile clients that
connect to a custom server port (but leaving that at 4500 is usually not a problem,
either).

== IKEv1

IKEv1 traffic is automatically handled by the xref:daemons/charon.adoc[`*charon*`]
daemon which supports NAT traversal according to {RFC3947}[RFC 3947] and some of
its early drafts without having to enable NAT traversal explicitly but it can't
be disabled either, though.
