= pkcs11 Plugin

== Purpose

The `*pkcs11*` plugin for `*libstrongswan*` implements the `PKCS#11` smart card
interface and can be used by both the IKE xref:daemons/charon.adoc[`*charon*`]
daemon and the xref:pki/pki.adoc[pki] tool. Besides `RSA` keys the plugin also
supports `ECDSA`, `DH/ECDH` and `RNG`.

The plugin is disabled by default and can be enabled with the
xref:install/autoconf.adoc[`*./configure*`] option

 --enable-pkcs11

== Configuration

The `*pkcs11*` plugin is configured using the following options in the
xref:config/strongswanConf.adoc#_charon_plugins_pkcs11[`*charon.plugins.pkcs11*`]
section of xref:config/strongswanConf.adoc[`*strongswan.conf*`]:

[cols="9,1,10"]
|===
|Key|Default|Description

include::partial$config/plugins/pkcs11.adoc[]
|===

Example:
----
libstrongswan {
  # ...
  plugins {
    pkcs11 {
      modules {
        my-xy-module {
          path = /path/to/pkcs11/lib.so
        }
      }
    }
  }
}
----

== Behavior

Certificates stored on smart cards are loaded automatically when the daemon is
started. If the `PKCS#11` module supports hot-plugging, the certificates are
reloaded when a token gets inserted or removed later. The first certificate
matching the local identity

 connections.<conn>.local<suffix>.id

in xref:swanctl/swanctlConf.adoc[swanctl.conf] will be used.

Specific certificates can also be loaded via xref:swanctl/swanctlConf.adoc[swanctl.conf]
using sections of the form

 connections.<conn>.local<suffix>.cert<suffix>

To access the private key you have to specify the associated PIN in
xref:swanctl/swanctlConf.adoc[swanctl.conf] in section of the form

  secrets.token<suffix>

Depending on the configuration reloading the secrets will prompt the user for
the PIN.

[[NetworkManager#Smart-card-requirements|NetworkManager]] makes the use of
smart cards with IKEv2 even easier.
