= TNC Server

:TCG:   https://trustedcomputinggroup.org
:IFIMV: {TCG}/wp-content/uploads/TNC_IFIMV_v1_4_r11.pdf

== Installation

In order to run a TNC server communicating via PT-EAP, in addition to the standard
strongSwan VPN configuration the following
xref:install/autoconf.adoc[`*./configure*`] options have to be enabled

 --enable-eap-identity --enable-eap-ttls --enable-eap-tnc --enable-tnccs-20 --enable-tnc-imv

If client authentication is based on passwords instead of X.509 certificates,
additionally either the EAP-MD5 or EAP-MSCHAPv2 methods have to be enabled with
`--enable-eap-md5` or `--enable-eap-mschapv2`, respectively.

----
# strongSwan configuration file

charon {
  start-scripts {
    creds = swanctl --load-creds
    conns = swanctl --load-conns
    pools = swanctl --load-pools
  }
  filelog {
    stderr {
      default = 1
      tnc = 2
      imv = 2
    }
  }
  fragment_size = 1500

  plugins {
    eap-ttls {
      max_message_count = 0
      # enable for certificate-based client authentication
      request_peer_auth = yes
      phase2_piggyback = yes
      phase2_method = md5
      phase2_tnc = yes
    }
    eap-tnc {
      max_message_count = 0
    }
    tnccs-20 {
      max_batch_size   = 32754
      max_message_size = 32722
    }
  }
}

libimcv {
  database = sqlite:///etc/pts/config.db
  policy_script = /usr/libexec/ipsec/imv_policy_manager
}

libtls {
  suites = TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
}
----

== Integrity Measurement Verifiers

Any number of Integrity Measurement Verifiers (IMVs) can be attached to a TNC Server.
An IMV is a dynamic library which communicates with the TNC Server via the
{IFIMV}[TNC IF-IMV] API defined in the form of a C header file. The `*/etc/tnc_config*`
file tells the TNC Server which IMVs are to be loaded:
----
#IMV-Configuration

IMV "OS"             /usr/lib/ipsec/imcvs/imv-os.so
IMV "Scanner"        /usr/lib/ipsec/imcvs/imv-scanner.so
# IMV "SWIMA"        /usr/lib/ipsec/imcvs/imv-swima.so
# IMV "Attestation"  /usr/lib/ipsec/imcvs/imv-attestation.so
----
When the xref:daemons/charon.adoc[`*charon*`] daemon starts up, the IMVs are loaded.
In our example the IMV 1 `*OS*` and IMV 2 `*Scanner*` are enabled which subcribe to
PA-TNC message subtypes `*IETF/Operating System*` and `*IETF/Firewall*`, respectively.
----
00[DMN] Starting IKE charon daemon (strongSwan 5.9.5, Linux 5.13.0-35-generic, x86_64)
00[TNC] TNC recommendation policy is 'default'
00[TNC] loading IMVs from '/etc/tnc_config'
00[TNC] added IETF attributes
00[TNC] added ITA-HSR attributes
00[TNC] added PWG attributes
00[TNC] added TCG attributes
00[LIB] libimcv initialized
00[IMV] IMV 1 "OS" initialized
00[TNC] IMV 1 supports 1 message type: 'IETF/Operating System' 0x000000/0x00000001
00[TNC] IMV 1 "OS" loaded from '/usr/lib/ipsec/imcvs/imv-os.so'
00[IMV] IMV 2 "Scanner" initialized
00[TNC] IMV 2 supports 1 message type: 'IETF/Firewall' 0x000000/0x00000005
00[TNC] IMV 2 "Scanner" loaded from '/usr/lib/ipsec/imcvs/imv-scanner.so'
----
After xref:daemons/charon.adoc[`*charon*`] has loaded all its plugins and spawned
16 worker threads, the xref:swanctl/swanctl.adoc[`*swanctl*`] start scripts load
the credentials, the connection configurations and the pool definitions.
----
00[LIB] loaded plugins: charon random nonce x509 constraints pubkey pem openssl sqlite kernel-netlink resolve socket-default vici updown eap-identity eap-md5 eap-ttls eap-tnc tnc-imv tnc-tnccs tnccs-20
00[JOB] spawning 16 worker threads

00[DMN] executing start script 'creds' (swanctl --load-creds)
01[CFG] loaded certificate 'C=CH, O=Cyber, CN=server.strongswan.org'
08[CFG] loaded certificate 'C=CH, O=Cyber, CN=Cyber Root CA'
12[CFG] loaded ECDSA private key
16[CFG] loaded EAP shared key with id 'eap-jane' for: 'jane'
09[CFG] loaded EAP shared key with id 'eap-hacker' for: 'hacker'
00[DMN] creds: loaded certificate from '/etc/swanctl/x509/serverCert.pem'
00[DMN] creds: loaded certificate from '/etc/swanctl/x509ca/caCert.pem'
00[DMN] creds: loaded ECDSA key from '/etc/swanctl/ecdsa/serverKey.pem'
00[DMN] creds: loaded eap secret 'eap-jane'
00[DMN] creds: loaded eap secret 'eap-hacker'

00[DMN] executing start script 'conns' (swanctl --load-conns)
07[CFG] added vici connection: tnc
00[DMN] conns: loaded connection 'tnc'
00[DMN] conns: successfully loaded 1 connections, 0 unloaded

00[DMN] executing start script 'pools' (swanctl --load-pools)
08[CFG] added vici pool rw_pool: 10.3.0.0, 254 entries
00[DMN] pools: loaded pool 'rw_pool'
00[DMN] pools: successfully loaded 1 pools, 0 unloaded
----

== TNC-Enabled VPN Server Configuration

The TNC-enabled VPN server configuration is based on the following
xref:swanctl/swanctlConf.adoc[`*swanctl.conf*`] file
----
connections {
  tnc {
    pools = rw_pool

    local {
      auth = eap-ttls
      certs = serverCert.pem
      id = server.strongswan.org
    }
    remote {
      auth = eap-ttls
      eap_id = %any
    }
    children {
      tnc {
        local_ts = 10.1.0.0/24,192.168.0.2
        esp_proposals = aes256gcm128-chacha20poly1305-x25519
       }
    }
    version = 2
    proposals = aes256-sha256-x25519
    send_certreq = no
  }
}

pools {
  rw_pool {
    addrs = 10.3.0.0/24
  }
}

secrets {
  eap-jane {
    id = jane
    secret = 3s9RFGdWE5EW
  }
  eap-hacker {
    id = hacker
    secret = K8FW9/N0VIAJ
  }
}
----
----
swanctl --list-conns
tnc: IKEv2, no reauthentication, rekeying every 14400s
  local:  %any
  remote: %any
  local EAP_TTLS authentication:
    id: server.strongswan.org
    certs: C=CH, O=Cyber, CN=server.strongswan.org
  remote EAP_TTLS authentication:
    eap_id: %any
  tnc: TUNNEL, rekeying every 3600s
    local:  10.1.0.0/24 192.168.0.2/32
    remote: dynamic
----

----
12[NET] received packet: from 192.168.0.3[500] to 192.168.0.2[500] (240 bytes)
12[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
12[IKE] 192.168.0.3 is initiating an IKE_SA
12[CFG] selected proposal: IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/CURVE_25519
12[ENC] generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(CHDLESS_SUP) N(MULT_AUTH) ]
12[NET] sending packet: from 192.168.0.2[500] to 192.168.0.3[500] (248 bytes)
----
----
14[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (272 bytes)
14[ENC] parsed IKE_AUTH request 1 [ IDi N(INIT_CONTACT) IDr CPRQ(ADDR DNS) SA TSi TSr N(MOBIKE_SUP) N(NO_ADD_ADDR) N(MULT_AUTH) N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
14[CFG] looking for peer configs matching 192.168.0.2[server.strongswan.org]...192.168.0.3[192.168.0.3]
14[CFG] selected peer config 'tnc'
14[IKE] initiating EAP_IDENTITY method (id 0x00)
14[IKE] peer supports MOBIKE
14[ENC] generating IKE_AUTH response 1 [ IDr EAP/REQ/ID ]
14[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (112 bytes)
----
----
16[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (96 bytes)
16[ENC] parsed IKE_AUTH request 2 [ EAP/RES/ID ]
16[IKE] received EAP identity 'client.strongswan.org'
16[IKE] initiating EAP_TTLS method (id 0x45)
16[ENC] generating IKE_AUTH response 2 [ EAP/REQ/TTLS ]
16[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (80 bytes)
----
----
05[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (272 bytes)
05[ENC] parsed IKE_AUTH request 3 [ EAP/RES/TTLS ]
05[TLS] using key of type ECDSA
05[TLS] negotiated TLS 1.2 using suite TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
05[TLS] sending TLS server certificate 'C=CH, O=Cyber, CN=server.strongswan.org'
05[ENC] generating IKE_AUTH response 3 [ EAP/REQ/TTLS ]
05[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (928 bytes)
----
----
01[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (880 bytes)
01[ENC] parsed IKE_AUTH request 4 [ EAP/RES/TTLS ]
01[TLS] received TLS peer certificate 'C=CH, O=Cyber, CN=client.strongswan.org'
01[CFG]   using certificate "C=CH, O=Cyber, CN=client.strongswan.org"
01[CFG]   using trusted ca certificate "C=CH, O=Cyber, CN=Cyber Root CA"
01[CFG]   reached self-signed root ca with a path length of 0
01[IKE] sending tunneled EAP-TTLS AVP [EAP/REQ/ID]
01[ENC] generating IKE_AUTH response 4 [ EAP/REQ/TTLS ]
01[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (176 bytes)
06[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (144 bytes)
06[ENC] parsed IKE_AUTH request 5 [ EAP/RES/TTLS ]
06[IKE] received tunneled EAP-TTLS AVP [EAP/RES/ID]
06[IKE] received EAP identity 'client.strongswan.org'
06[IKE] phase2 method EAP_PT_EAP selected
06[IKE] sending tunneled EAP-TTLS AVP [EAP/REQ/PT]
06[ENC] generating IKE_AUTH response 5 [ EAP/REQ/TTLS ]
06[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (128 bytes)
09[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (448 bytes)
09[ENC] parsed IKE_AUTH request 6 [ EAP/RES/TTLS ]
09[IKE] received tunneled EAP-TTLS AVP [EAP/RES/PT]
09[TNC] assigned TNCCS Connection ID 1
09[IMV] IMV 1 "OS" created a state for IF-TNCCS 2.0 Connection ID 1: +long +excl -soh
09[IMV]   over IF-T for Tunneled EAP 2.0 with maximum PA-TNC message size of 32722 bytes
09[IMV]   user AR identity 'client.strongswan.org' of type username authenticated by certificate
09[IMV]   machine AR identity '192.168.0.3' of type IPv4 address authenticated by unknown method
09[IMV] IMV 2 "Scanner" created a state for IF-TNCCS 2.0 Connection ID 1: +long +excl -soh
09[IMV]   over IF-T for Tunneled EAP 2.0 with maximum PA-TNC message size of 32722 bytes
09[IMV] IMV 1 "OS" changed state of Connection ID 1 to 'Handshake'
09[IMV] IMV 2 "Scanner" changed state of Connection ID 1 to 'Handshake'
09[TNC] received TNCCS batch (321 bytes)
09[TNC] TNC server is handling inbound connection
09[TNC] processing PB-TNC CDATA batch for Connection ID 1
09[TNC] PB-TNC state transition from 'Init' to 'Server Working'
09[TNC] processing IETF/PB-Language-Preference message (31 bytes)
09[TNC] processing IETF/PB-PA message (222 bytes)
09[TNC] processing IETF/PB-PA message (60 bytes)
09[TNC] setting language preference to 'en'
09[TNC] handling PB-PA message type 'IETF/Operating System' 0x000000/0x00000001
09[IMV] IMV 1 "OS" received message for Connection ID 1 from IMC 1
09[TNC] processing PA-TNC message with ID 0x0f74f43f
09[TNC] processing PA-TNC attribute type 'IETF/Product Information' 0x000000/0x00000002
09[TNC] processing PA-TNC attribute type 'IETF/String Version' 0x000000/0x00000004
09[TNC] processing PA-TNC attribute type 'IETF/Numeric Version' 0x000000/0x00000003
09[TNC] processing PA-TNC attribute type 'IETF/Operational Status' 0x000000/0x00000005
09[TNC] processing PA-TNC attribute type 'IETF/Forwarding Enabled' 0x000000/0x0000000b
09[TNC] processing PA-TNC attribute type 'IETF/Factory Default Password Enabled' 0x000000/0x0000000c
09[TNC] processing PA-TNC attribute type 'ITA-HSR/Device ID' 0x00902a/0x00000008
09[IMV] operating system name is 'Ubuntu' from vendor Canonical
09[IMV] operating system version is '20.04 x86_64'
09[IMV] operating system numeric version is 20.4
09[IMV] operational status: operational, result: successful
09[IMV] last boot: Mar 28 07:42:58 UTC 2022
09[IMV] IPv4 forwarding is enabled
09[IMV] factory default password is disabled
09[IMV] device ID is a488651e36664792b306cf8be72dd630
09[TNC] handling PB-PA message type 'IETF/Firewall' 0x000000/0x00000005
09[IMV] IMV 2 "Scanner" received message for Connection ID 1 from IMC 2
09[TNC] processing PA-TNC message with ID 0x0dc7be19
09[TNC] processing PA-TNC attribute type 'IETF/Port Filter' 0x000000/0x00000006
09[IMV] IMV 1 requests a segmentation contract for PA message type 'IETF/Operating System' 0x000000/0x00000001
09[IMV]   maximum attribute size of 100000000 bytes with maximum segment size of 32698 bytes
09[IMV] assigned session ID 1 to Connection ID 1
09[IMV] policy: imv_policy_manager start successful
09[IMV] PCKGS workitem 1
09[IMV] TCPOP workitem 2
09[IMV] UDPOP workitem 3
09[TNC]   0x000000/0x00000007 'IETF/Installed Packages'
09[IMV] IMV 1 handles PCKGS workitem 1
09[TNC] creating PA-TNC message with ID 0xc084b149
09[TNC] creating PA-TNC attribute type 'TCG/Max Attribute Size Request' 0x005597/0x00000021
09[TNC] creating PA-TNC attribute type 'IETF/Attribute Request' 0x000000/0x00000001
09[TNC] creating PB-PA message type 'IETF/Operating System' 0x000000/0x00000001
09[IMV] IMV 2 handles TCPOP workitem 2
09[IMV] IMV 2 handles UDPOP workitem 3
09[IMV] list of tcp ports that are allowed to be open:
09[IMV] tcp port 41963 open: fatal
09[IMV] IMV 2 handled TCPOP workitem 2: no access - violating tcp ports: 41963
09[IMV] list of udp ports that are allowed to be open:
09[IMV]   500 -   500
09[IMV]  4500 -  4500
09[IMV] 10000 - 65000
09[IMV] udp port  4500 open: ok
09[IMV] udp port 47753 open: ok
09[IMV] udp port   500 open: ok
09[IMV] IMV 2 handled UDPOP workitem 3: allow - no violating udp ports
09[TNC] creating PA-TNC message with ID 0x26d87477
09[TNC] creating PA-TNC attribute type 'IETF/Assessment Result' 0x000000/0x00000009
09[TNC] creating PA-TNC attribute type 'IETF/Remediation Instructions' 0x000000/0x0000000a
09[TNC] creating PB-PA message type 'IETF/Firewall' 0x000000/0x00000005
09[TNC] IMV 2 is setting reason string to 'Open server ports were detected'
09[TNC] IMV 2 is setting reason language to 'en'
09[TNC] IMV 2 provides recommendation 'no access' and evaluation 'non-compliant minor'
09[TNC] TNC server is handling outbound connection
09[TNC] PB-TNC state transition from 'Server Working' to 'Client Working'
09[TNC] creating PB-TNC SDATA batch
09[TNC] adding IETF/PB-PA message
09[TNC] adding IETF/PB-PA message
09[TNC] sending PB-TNC SDATA batch (512 bytes) for Connection ID 1
09[IKE] sending tunneled EAP-TTLS AVP [EAP/REQ/PT]
09[ENC] generating IKE_AUTH response 6 [ EAP/REQ/TTLS ]
09[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (640 bytes)
07[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (1104 bytes)
07[ENC] parsed IKE_AUTH request 7 [ EAP/RES/TTLS ]
07[ENC] generating IKE_AUTH response 7 [ EAP/REQ/TTLS ]
07[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (80 bytes)
08[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (1104 bytes)
08[ENC] parsed IKE_AUTH request 8 [ EAP/RES/TTLS ]
08[ENC] generating IKE_AUTH response 8 [ EAP/REQ/TTLS ]
08[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (80 bytes)
10[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (944 bytes)
10[ENC] parsed IKE_AUTH request 9 [ EAP/RES/TTLS ]
10[IKE] received tunneled EAP-TTLS AVP [EAP/RES/PT]
10[TNC] received TNCCS batch (2845 bytes)
10[TNC] TNC server is handling inbound connection
10[TNC] processing PB-TNC CDATA batch for Connection ID 1
10[TNC] PB-TNC state transition from 'Client Working' to 'Server Working'
10[TNC] processing IETF/PB-PA message (2837 bytes)
10[TNC] handling PB-PA message type 'IETF/Operating System' 0x000000/0x00000001
10[IMV] IMV 1 "OS" received message for Connection ID 1 from IMC 1 to IMV 1
10[TNC] processing PA-TNC message with ID 0x6e31e351
10[TNC] processing PA-TNC attribute type 'TCG/Max Attribute Size Response' 0x005597/0x00000022
10[TNC] processing PA-TNC attribute type 'IETF/Installed Packages' 0x000000/0x00000007
10[IMV] IMV 1 received a segmentation contract response from IMC 1 for PA message type 'IETF/Operating System' 0x000000/0x00000001
10[IMV]   maximum attribute size of 100000000 bytes with maximum segment size of 32698 bytes
10[IMV] processing installed 'Ubuntu 20.04 x86_64' packages
10[IMV] package 'adduser' (3.118ubuntu2) not found
10[IMV] package 'apt' (2.0.4) not found
10[IMV] package 'base-files' (11ubuntu5.3) not found
10[IMV] package 'base-passwd' (3.5.47) not found
10[IMV] package 'bash' (5.0-6ubuntu1.1) not found
10[IMV] package 'bsdutils' (1:2.34-0.1ubuntu9.1) not found
10[IMV] package 'bzip2' (1.0.8-2) not found
10[IMV] package 'ca-certificates' (20210119~20.04.2) not found
10[IMV] package 'coreutils' (8.30-3ubuntu2) not found
10[IMV] package 'dash' (0.5.10.2-6) not found
10[IMV] package 'debconf' (1.5.73) not found
10[IMV] package 'debianutils' (4.9.1) not found
10[IMV] package 'diffutils' (1:3.7-3) not found
10[IMV] package 'dpkg' (1.19.7ubuntu3) not found
10[IMV] package 'e2fsprogs' (1.45.5-2ubuntu1) not found
10[IMV] package 'fdisk' (2.34-0.1ubuntu9.1) not found
10[IMV] package 'findutils' (4.7.0-1ubuntu1) not found
10[IMV] package 'gcc-10-base' (10.3.0-1ubuntu1~20.04) not found
10[IMV] package 'gpgv' (2.2.19-3ubuntu2.1) not found
10[IMV] package 'grep' (3.4-1) not found
10[IMV] package 'gzip' (1.10-0ubuntu4) not found
10[IMV] package 'hostname' (3.23) not found
10[IMV] package 'init-system-helpers' (1.57) not found
10[IMV] package 'iproute2' (5.5.0-1ubuntu1) not found
10[IMV] package 'iputils-ping' (3:20190709-3) not found
10[IMV] package 'libacl1' (2.2.53-6) not found
10[IMV] package 'libapt-pkg6.0' (2.0.4) not found
10[IMV] package 'libatm1' (1:2.5.1-4) not found
10[IMV] package 'libattr1' (1:2.4.48-5) not found
10[IMV] package 'libaudit-common' (1:2.8.5-2ubuntu6) not found
10[IMV] package 'libaudit1' (1:2.8.5-2ubuntu6) not found
10[IMV] package 'libblkid1' (2.34-0.1ubuntu9.1) not found
10[IMV] package 'libbsd0' (0.10.0-1) not found
10[IMV] package 'libbz2-1.0' (1.0.8-2) not found
10[IMV] package 'libc-bin' (2.31-0ubuntu9.2) not found
10[IMV] package 'libc6' (2.31-0ubuntu9.7) not found
10[IMV] package 'libcap-ng0' (0.7.9-2.1build1) not found
10[IMV] package 'libcap2' (1:2.32-1) not found
10[IMV] package 'libcap2-bin' (1:2.32-1) not found
10[IMV] package 'libcom-err2' (1.45.5-2ubuntu1) not found
10[IMV] package 'libcrypt1' (1:4.4.10-10ubuntu4) not found
10[IMV] package 'libdb5.3' (5.3.28+dfsg1-0.6ubuntu2) not found
10[IMV] package 'libdebconfclient0' (0.251ubuntu1) not found
10[IMV] package 'libelf1' (0.176-1.1build1) not found
10[IMV] package 'libext2fs2' (1.45.5-2ubuntu1) not found
10[IMV] package 'libfdisk1' (2.34-0.1ubuntu9.1) not found
10[IMV] package 'libffi7' (3.3-4) not found
10[IMV] package 'libgcc-s1' (10.3.0-1ubuntu1~20.04) not found
10[IMV] package 'libgcrypt20' (1.8.5-5ubuntu1) not found
10[IMV] package 'libgmp10' (2:6.2.0+dfsg-4) not found
10[IMV] package 'libgnutls30' (3.6.13-2ubuntu1.3) not found
10[IMV] package 'libgpg-error0' (1.37-1) not found
10[IMV] package 'libhogweed5' (3.5.1+really3.5.1-2) not found
10[IMV] package 'libidn2-0' (2.2.0-2) not found
10[IMV] package 'libjson-c4' (0.13.1+dfsg-7ubuntu0.3) not found
10[IMV] package 'liblz4-1' (1.9.2-2) not found
10[IMV] package 'liblzma5' (5.2.4-1ubuntu1) not found
10[IMV] package 'libmnl0' (1.0.4-2) not found
10[IMV] package 'libmount1' (2.34-0.1ubuntu9.1) not found
10[IMV] package 'libncurses6' (6.2-0ubuntu2) not found
10[IMV] package 'libncursesw6' (6.2-0ubuntu2) not found
10[IMV] package 'libnettle7' (3.5.1+really3.5.1-2) not found
10[IMV] package 'libp11-kit0' (0.23.20-1ubuntu0.1) not found
10[IMV] package 'libpam-cap' (1:2.32-1) not found
10[IMV] package 'libpam-modules' (1.3.1-5ubuntu4.1) not found
10[IMV] package 'libpam-modules-bin' (1.3.1-5ubuntu4.1) not found
10[IMV] package 'libpam-runtime' (1.3.1-5ubuntu4.1) not found
10[IMV] package 'libpam0g' (1.3.1-5ubuntu4.1) not found
10[IMV] package 'libpcre2-8-0' (10.34-7) not found
10[IMV] package 'libpcre3' (2:8.39-12build1) not found
10[IMV] package 'libprocps8' (2:3.3.16-1ubuntu2) not found
10[IMV] package 'libreadline8' (8.0-4) not found
10[IMV] package 'libseccomp2' (2.4.3-1ubuntu3.20.04.3) not found
10[IMV] package 'libselinux1' (3.0-1build2) not found
10[IMV] package 'libsemanage-common' (3.0-1build2) not found
10[IMV] package 'libsemanage1' (3.0-1build2) not found
10[IMV] package 'libsepol1' (3.0-1) not found
10[IMV] package 'libsmartcols1' (2.34-0.1ubuntu9.1) not found
10[IMV] package 'libsqlite3-0' (3.31.1-4ubuntu0.2) not found
10[IMV] package 'libss2' (1.45.5-2ubuntu1) not found
10[IMV] package 'libssl1.1' (1.1.1f-1ubuntu2.12) not found
10[IMV] package 'libstdc++6' (10.3.0-1ubuntu1~20.04) not found
10[IMV] package 'libsystemd0' (245.4-4ubuntu3.4) not found
10[IMV] package 'libtasn1-6' (4.16.0-2) not found
10[IMV] package 'libtinfo6' (6.2-0ubuntu2) not found
10[IMV] package 'libudev1' (245.4-4ubuntu3.4) not found
10[IMV] package 'libunistring2' (0.9.10-2) not found
10[IMV] package 'libuuid1' (2.34-0.1ubuntu9.1) not found
10[IMV] package 'libxtables12' (1.8.4-3ubuntu2) not found
10[IMV] package 'libzstd1' (1.4.4+dfsg-3) not found
10[IMV] package 'login' (1:4.8.1-1ubuntu5.20.04) not found
10[IMV] package 'logsave' (1.45.5-2ubuntu1) not found
10[IMV] package 'lsb-base' (11.1.0ubuntu2) not found
10[IMV] package 'mawk' (1.3.4.20200120-2) not found
10[IMV] package 'mount' (2.34-0.1ubuntu9.1) not found
10[IMV] package 'nano' (4.8-1ubuntu1) not found
10[IMV] package 'ncurses-base' (6.2-0ubuntu2) not found
10[IMV] package 'ncurses-bin' (6.2-0ubuntu2) not found
10[IMV] package 'net-tools' (1.60+git20180626.aebd88e-1ubuntu1) not found
10[IMV] package 'openssl' (1.1.1f-1ubuntu2.12) unknown
10[IMV] package 'passwd' (1:4.8.1-1ubuntu5.20.04) not found
10[IMV] package 'perl-base' (5.30.0-9ubuntu0.2) not found
10[IMV] package 'procps' (2:3.3.16-1ubuntu2) not found
10[IMV] package 'readline-common' (8.0-4) not found
10[IMV] package 'sed' (4.7-1) not found
10[IMV] package 'sensible-utils' (0.0.12+nmu1) not found
10[IMV] package 'sqlite3' (3.31.1-4ubuntu0.2) not found
10[IMV] package 'sysvinit-utils' (2.96-2.1ubuntu1) not found
10[IMV] package 'tar' (1.30+dfsg-7ubuntu0.20.04.1) not found
10[IMV] package 'ubuntu-keyring' (2020.02.11.2) not found
10[IMV] package 'util-linux' (2.34-0.1ubuntu9.1) not found
10[IMV] package 'zlib1g' (1:1.2.11.dfsg-2ubuntu1.2) not found
10[IMV] IMV 1 handled PCKGS workitem 1: allow - processed 112 packages: 0 vulnerable, 0 blacklisted, 0 ok, 112 unknown
10[TNC] creating PA-TNC message with ID 0x8341ae40
10[TNC] creating PA-TNC attribute type 'IETF/Assessment Result' 0x000000/0x00000009
10[TNC] creating PB-PA message type 'IETF/Operating System' 0x000000/0x00000001
10[TNC] IMV 1 provides recommendation 'allow' and evaluation 'compliant'
10[TNC] TNC server is handling outbound connection
10[IMV] policy: recommendation for access requestor 192.168.0.3 is no access
10[IMV] policy: imv_policy_manager stop successful
10[IMV] IMV 1 "OS" changed state of Connection ID 1 to 'None'
10[IMV] IMV 2 "Scanner" changed state of Connection ID 1 to 'None'
10[TNC] PB-TNC state transition from 'Server Working' to 'Decided'
10[TNC] creating PB-TNC RESULT batch
10[TNC] adding IETF/PB-PA message
10[TNC] adding IETF/PB-Assessment-Result message
10[TNC] adding IETF/PB-Access-Recommendation message
10[TNC] adding IETF/PB-Reason-String message
10[TNC] sending PB-TNC RESULT batch (138 bytes) for Connection ID 1
10[IKE] sending tunneled EAP-TTLS AVP [EAP/REQ/PT]
10[ENC] generating IKE_AUTH response 9 [ EAP/REQ/TTLS ]
10[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (272 bytes)
13[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (144 bytes)
13[ENC] parsed IKE_AUTH request 10 [ EAP/RES/TTLS ]
13[IKE] received tunneled EAP-TTLS AVP [EAP/RES/PT]
13[TNC] received TNCCS batch (8 bytes)
13[TNC] TNC server is handling inbound connection
13[TNC] processing PB-TNC CLOSE batch for Connection ID 1
13[TNC] PB-TNC state transition from 'Decided' to 'End'
13[TNC] final recommendation is 'no access' and evaluation is 'non-compliant minor'
13[TNC] policy enforced on peer '192.168.0.3' is 'no access'
13[IKE] EAP_PT_EAP method failed
13[TLS] sending TLS close notify
13[ENC] generating IKE_AUTH response 10 [ EAP/REQ/TTLS ]
13[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (112 bytes)
11[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (112 bytes)
11[ENC] parsed IKE_AUTH request 11 [ EAP/RES/TTLS ]
11[IKE] EAP method EAP_TTLS failed for peer 192.168.0.3
11[ENC] generating IKE_AUTH response 11 [ EAP/FAIL ]
11[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (80 bytes)
11[IMV] IMV 1 "OS" deleted the state of Connection ID 1
11[IMV] IMV 2 "Scanner" deleted the state of Connection ID 1
11[TNC] removed TNCCS Connection ID 1

--------------------------------------------------------------------------------
swanctl --list-conns
tnc: IKEv2, no reauthentication, rekeying every 14400s
  local:  %any
  remote: %any
  local EAP_TTLS authentication:
    id: server.strongswan.org
    certs: C=CH, O=Cyber, CN=server.strongswan.org
  remote EAP_TTLS authentication:
    eap_id: %any
  tnc: TUNNEL, rekeying every 3600s
    local:  10.1.0.0/24 192.168.0.2/32
    remote: dynamic

12[NET] received packet: from 192.168.0.3[500] to 192.168.0.2[500] (240 bytes)
12[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
12[IKE] 192.168.0.3 is initiating an IKE_SA
12[CFG] selected proposal: IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/CURVE_25519
12[ENC] generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(CHDLESS_SUP) N(MULT_AUTH) ]
12[NET] sending packet: from 192.168.0.2[500] to 192.168.0.3[500] (248 bytes)
11[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (272 bytes)
11[ENC] parsed IKE_AUTH request 1 [ IDi N(INIT_CONTACT) IDr CPRQ(ADDR DNS) SA TSi TSr N(MOBIKE_SUP) N(NO_ADD_ADDR) N(MULT_AUTH) N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
11[CFG] looking for peer configs matching 192.168.0.2[server.strongswan.org]...192.168.0.3[192.168.0.3]
11[CFG] selected peer config 'tnc'
11[IKE] initiating EAP_IDENTITY method (id 0x00)
11[IKE] peer supports MOBIKE
11[ENC] generating IKE_AUTH response 1 [ IDr EAP/REQ/ID ]
11[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (112 bytes)
01[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (80 bytes)
01[ENC] parsed IKE_AUTH request 2 [ EAP/RES/ID ]
01[IKE] received EAP identity 'hacker'
01[IKE] initiating EAP_TTLS method (id 0x86)
01[ENC] generating IKE_AUTH response 2 [ EAP/REQ/TTLS ]
01[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (80 bytes)
06[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (272 bytes)
06[ENC] parsed IKE_AUTH request 3 [ EAP/RES/TTLS ]
06[TLS] using key of type ECDSA
06[TLS] negotiated TLS 1.2 using suite TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
06[TLS] sending TLS server certificate 'C=CH, O=Cyber, CN=server.strongswan.org'
06[ENC] generating IKE_AUTH response 3 [ EAP/REQ/TTLS ]
06[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (896 bytes)
15[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (240 bytes)
15[ENC] parsed IKE_AUTH request 4 [ EAP/RES/TTLS ]
15[IKE] sending tunneled EAP-TTLS AVP [EAP/REQ/ID]
15[ENC] generating IKE_AUTH response 4 [ EAP/REQ/TTLS ]
15[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (176 bytes)
05[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (128 bytes)
05[ENC] parsed IKE_AUTH request 5 [ EAP/RES/TTLS ]
05[IKE] received tunneled EAP-TTLS AVP [EAP/RES/ID]
05[IKE] received EAP identity 'hacker'
05[IKE] phase2 method EAP_MD5 selected
05[IKE] sending tunneled EAP-TTLS AVP [EAP/REQ/MD5]
05[ENC] generating IKE_AUTH response 5 [ EAP/REQ/TTLS ]
05[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (144 bytes)
09[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (144 bytes)
09[ENC] parsed IKE_AUTH request 6 [ EAP/RES/TTLS ]
09[IKE] received tunneled EAP-TTLS AVP [EAP/RES/MD5]
09[IKE] EAP_TTLS phase2 authentication of 'hacker' with EAP_MD5 successful
09[IKE] phase2 method EAP_PT_EAP selected
09[IKE] sending tunneled EAP-TTLS AVP [EAP/REQ/PT]
09[ENC] generating IKE_AUTH response 6 [ EAP/REQ/TTLS ]
09[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (128 bytes)
08[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (448 bytes)
08[ENC] parsed IKE_AUTH request 7 [ EAP/RES/TTLS ]
08[IKE] received tunneled EAP-TTLS AVP [EAP/RES/PT]
08[TNC] assigned TNCCS Connection ID 1
08[IMV] IMV 1 "OS" created a state for IF-TNCCS 2.0 Connection ID 1: +long +excl -soh
08[IMV]   over IF-T for Tunneled EAP 2.0 with maximum PA-TNC message size of 32722 bytes
08[IMV]   user AR identity 'hacker' of type username authenticated by password
08[IMV]   machine AR identity '192.168.0.3' of type IPv4 address authenticated by unknown method
08[IMV] IMV 2 "Scanner" created a state for IF-TNCCS 2.0 Connection ID 1: +long +excl -soh
08[IMV]   over IF-T for Tunneled EAP 2.0 with maximum PA-TNC message size of 32722 bytes
08[IMV] IMV 1 "OS" changed state of Connection ID 1 to 'Handshake'
08[IMV] IMV 2 "Scanner" changed state of Connection ID 1 to 'Handshake'
---------------------------------------------------------------------------------
08[TNC] received TNCCS batch (321 bytes)
08[TNC] TNC server is handling inbound connection
08[TNC] processing PB-TNC CDATA batch for Connection ID 1
08[TNC] PB-TNC state transition from 'Init' to 'Server Working'
08[TNC] processing IETF/PB-Language-Preference message (31 bytes)
08[TNC] processing IETF/PB-PA message (222 bytes)
08[TNC] processing IETF/PB-PA message (60 bytes)
08[TNC] setting language preference to 'en'
08[TNC] handling PB-PA message type 'IETF/Operating System' 0x000000/0x00000001
08[IMV] IMV 1 "OS" received message for Connection ID 1 from IMC 1
08[TNC] processing PA-TNC message with ID 0xfecc91f5
08[TNC] processing PA-TNC attribute type 'IETF/Product Information' 0x000000/0x00000002
08[TNC] processing PA-TNC attribute type 'IETF/String Version' 0x000000/0x00000004
08[TNC] processing PA-TNC attribute type 'IETF/Numeric Version' 0x000000/0x00000003
08[TNC] processing PA-TNC attribute type 'IETF/Operational Status' 0x000000/0x00000005
08[TNC] processing PA-TNC attribute type 'IETF/Forwarding Enabled' 0x000000/0x0000000b
08[TNC] processing PA-TNC attribute type 'IETF/Factory Default Password Enabled' 0x000000/0x0000000c
08[TNC] processing PA-TNC attribute type 'ITA-HSR/Device ID' 0x00902a/0x00000008
08[IMV] operating system name is 'Ubuntu' from vendor Canonical
08[IMV] operating system version is '20.04 x86_64'
08[IMV] operating system numeric version is 20.4
08[IMV] operational status: operational, result: successful
08[IMV] last boot: Mar 28 07:43:03 UTC 2022
08[IMV] IPv4 forwarding is enabled
08[IMV] factory default password is disabled
08[IMV] device ID is a488651e36664792b306cf8be72dd630
08[TNC] handling PB-PA message type 'IETF/Firewall' 0x000000/0x00000005
08[IMV] IMV 2 "Scanner" received message for Connection ID 1 from IMC 2
08[TNC] processing PA-TNC message with ID 0x3a7d7432
08[TNC] processing PA-TNC attribute type 'IETF/Port Filter' 0x000000/0x00000006
08[IMV] IMV 1 requests a segmentation contract for PA message type 'IETF/Operating System' 0x000000/0x00000001
08[IMV]   maximum attribute size of 100000000 bytes with maximum segment size of 32698 bytes
08[IMV] assigned session ID 2 to Connection ID 1
08[IMV] policy: imv_policy_manager start successful
08[IMV] policy: skipping enforcement 1
08[IMV] TCPOP workitem 4
08[IMV] UDPOP workitem 5
08[IMV] IMV 1 has no workitems - no evaluation requested
08[TNC] creating PA-TNC message with ID 0xb37173d9
08[TNC] creating PA-TNC attribute type 'IETF/Assessment Result' 0x000000/0x00000009
08[TNC] creating PA-TNC attribute type 'IETF/Remediation Instructions' 0x000000/0x0000000a
08[TNC] creating PB-PA message type 'IETF/Operating System' 0x000000/0x00000001
08[TNC] IMV 1 provides recommendation 'allow' and evaluation 'don't know'
08[IMV] IMV 2 handles TCPOP workitem 4
08[IMV] IMV 2 handles UDPOP workitem 5
08[IMV] list of tcp ports that are allowed to be open:
08[IMV] tcp port 46001 open: fatal
08[IMV] IMV 2 handled TCPOP workitem 4: no access - violating tcp ports: 46001
08[IMV] list of udp ports that are allowed to be open:
08[IMV]   500 -   500
08[IMV]  4500 -  4500
08[IMV] 10000 - 65000
08[IMV] udp port  4500 open: ok
08[IMV] udp port 41252 open: ok
08[IMV] udp port   500 open: ok
08[IMV] IMV 2 handled UDPOP workitem 5: allow - no violating udp ports
08[TNC] creating PA-TNC message with ID 0x4fca0837
08[TNC] creating PA-TNC attribute type 'IETF/Assessment Result' 0x000000/0x00000009
08[TNC] creating PA-TNC attribute type 'IETF/Remediation Instructions' 0x000000/0x0000000a
08[TNC] creating PB-PA message type 'IETF/Firewall' 0x000000/0x00000005
08[TNC] IMV 2 is setting reason string to 'Open server ports were detected'
08[TNC] IMV 2 is setting reason language to 'en'
08[TNC] IMV 2 provides recommendation 'no access' and evaluation 'non-compliant minor'
08[TNC] TNC server is handling outbound connection
08[IMV] policy: recommendation for access requestor 192.168.0.3 is no access
08[IMV] policy: imv_policy_manager stop successful
08[IMV] IMV 1 "OS" changed state of Connection ID 1 to 'None'
08[IMV] IMV 2 "Scanner" changed state of Connection ID 1 to 'None'
08[TNC] PB-TNC state transition from 'Server Working' to 'Decided'
08[TNC] creating PB-TNC RESULT batch
08[TNC] adding IETF/PB-PA message
08[TNC] adding IETF/PB-PA message
08[TNC] adding IETF/PB-Assessment-Result message
08[TNC] adding IETF/PB-Access-Recommendation message
08[TNC] adding IETF/PB-Reason-String message
08[TNC] sending PB-TNC RESULT batch (663 bytes) for Connection ID 1
08[IKE] sending tunneled EAP-TTLS AVP [EAP/REQ/PT]
08[ENC] generating IKE_AUTH response 7 [ EAP/REQ/TTLS ]
08[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (800 bytes)
07[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (144 bytes)
07[ENC] parsed IKE_AUTH request 8 [ EAP/RES/TTLS ]
07[IKE] received tunneled EAP-TTLS AVP [EAP/RES/PT]
07[TNC] received TNCCS batch (8 bytes)
07[TNC] TNC server is handling inbound connection
07[TNC] processing PB-TNC CLOSE batch for Connection ID 1
07[TNC] PB-TNC state transition from 'Decided' to 'End'
07[TNC] final recommendation is 'no access' and evaluation is 'non-compliant minor'
07[TNC] policy enforced on peer '192.168.0.3' is 'no access'
07[IKE] EAP_PT_EAP method failed
07[TLS] sending TLS close notify
07[ENC] generating IKE_AUTH response 8 [ EAP/REQ/TTLS ]
07[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (112 bytes)
10[NET] received packet: from 192.168.0.3[4500] to 192.168.0.2[4500] (112 bytes)
10[ENC] parsed IKE_AUTH request 9 [ EAP/RES/TTLS ]
10[IKE] EAP method EAP_TTLS failed for peer 192.168.0.3
10[ENC] generating IKE_AUTH response 9 [ EAP/FAIL ]
10[NET] sending packet: from 192.168.0.2[4500] to 192.168.0.3[4500] (80 bytes)
10[IMV] IMV 1 "OS" deleted the state of Connection ID 1
10[IMV] IMV 2 "Scanner" deleted the state of Connection ID 1
10[TNC] removed TNCCS Connection ID 1

# /usr/libexec/ipsec/attest --sessions
   2: Mar 29 09:15:29 2022  1 Ubuntu 20.04 x86_64  a488651e36664792b306 hacker - no access
   1: Mar 29 06:30:45 2022  1 Ubuntu 20.04 x86_64  a488651e36664792b306 client.strongswan.org - no access
# /usr/libexec/ipsec/attest --devices
   1: - a488651e36664792b306cf8be72dd630 - Ubuntu 20.04 x86_64 -
   2:   Mar 29 09:15:29 2022 hacker - no access
   1:   Mar 29 06:30:45 2022 client.strongswan.org - no access
1 device found
